### PR TITLE
Update VisionAPIHelper.java

### PR DESCRIPTION
**Pull request by sylee0506**
- used comparable interface

### CODE REVIEW

**Comment by sylee0506** [comment]
My original branch 'sylee' keeps making merge conflict, so I created different 2 temporary branches to commit.
It they are merged with master, I will delete them and re-clone to my original 'sylee' branch.

**Review by tranHieuDev23 — COMMENTED** [review]
Technically, the way you implement can work, but you have to add new, redundant properties in the class (such as the `Comparable` interface, `String description`, `float score`) which are not related to the function of the class. How about creating a private class inside that serves only to represent results from the Vision API? It will look somewhat like this:

```
public class VisionApiHelper {
    // Something something...

    private class Result implements Comparable<Result> {
        @Override
        public int compareTo(VisionAPIHelper v) { //sorted by score ; descending order
            if (score < v.score)
                return 1;
            else if (score > v.score)
                return -1;
            return 0;
    }

    // Something something...
}
```
Also, when gathering results from different images, it would be better to use a dynamic collection type, such as `List`, instead of an array. Same with the final results - `List` has a method to return an array of its elements.

**Comment by sylee0506** [comment]
@tranHieuDev23 Thanks for your feedback! I've changed that you mentioned.

**Review by tranHieuDev23 — APPROVED** [review]
There was two small bugs - a missing semicolon, and you used the `[]` operator instead of `.get(index)` with the `List`. I fixed them for you.

**Comment by sylee0506** [comment]
Oh yes, I was not able to compile them since I was in hurry to modify them before our meeting.😭 Thanks for your check.

**Pull request merged**
