### PR TITLE
Added Vision API Helper

### PR DESCRIPTION
**Pull request by sylee0506**
- Input: byte stream from blob
- Added two version
1) predictLabels : returns array of predicted labels, sorted by relevance
2) predictLandmarks : returns string of predicted landmark infos, in form of "landmark , latitude: longitude:"

### CODE REVIEW

**Comment by tranHieuDev23** [comment]
The code looks fine, but please don't change the API - the point of having an API is that other people's code can work with each other based on a previous agreement. My code is using the original method's name and input types, so this would cause conflict and the server would not run. Can you change them so that they have the original name and inputs?

**Comment by sylee0506** [comment]
Oh, I’m sorry for changing the name; I just tried to seperate two APIs, I will change it right away.

Before revising them, I had some questions during coding.
1) In terms of input of api, why do we need list of byte streams? I thought this api get a single image as input and returns api result about that image. That’s why I changed input type as a single byte stream.
2) In terms of output of api, is it okay to return result as list type? The previous code was string type, but as you marked in the comment, it needs to return something like array type.(which stores “result label” at each index)

I couldn’t think of these problems when I first reviewed the code. I got confused during implementing them.
Sorry for bothering, and if you give feedback, I will modify them accordingly.

**Comment by tranHieuDev23** [comment]
About the questions you asked:

1. The input needs a list of byte streams because we are detecting tags for one post at a time, and a post can have multiple images. So the tags a post can have depend on every image it has - hence the byte stream. I'm following [this response](https://stackoverflow.com/a/2424824) on StackOverflow about handling uploaded files in Java Servlet, which used their `InputStream`s.
2. The method's results are tags, so it should return an array of tag names (string). A Java `List` can be a list of generic objects, unless you declare it as `List<String>`.

**Comment by sylee0506** [comment]
If this code is ok, I will resolve conflict and merge them.
This PR is just for code review before our tomorrow's meeting!

**Review by tranHieuDev23 — COMMENTED** [review]
- Instead of combining the score and the description into a string and sort them, maybe you should create a private class with the `Comparable` interface and two properties of `score` and `description`. This way, you can sort any collection of them based on their score. I don't think comparing strings are very reliable.
- Please don't change the method name - it's predictTags instead of predictLabels.

**Comment by sylee0506** [comment]
I will shut this down and upload new PR to avoid merge conflicts.

**Pull request closed without merging**
