### PR TITLE
Handle tag name with URL-unfriendly characters

### PR DESCRIPTION
**Pull request by tranHieuDev23**
- Accents (such as Vietnamese symbols) are replaced with their ASCII counterparts.
- Whitespaces are compressed and replaced with underscores.
- Other URL-unsafe characters are removed.
Issues: The Vietnamese character `Đ` is not handled correctly. Please test with Korean characters and other Unicode string as well.

### CODE REVIEW

**Comment by suyeon0506** [comment]
Ok, I will test with Korean characters.

**Review by sylee0506 — APPROVED** [review]
Ok, I will test with Korean characters.

**Comment by tranHieuDev23** [comment]
I forgot! The code is deployed at [https://2-dot-su19-codeu-53-5533.appspot.com](https://2-dot-su19-codeu-53-5533.appspot.com), instead of the main version.

**Comment by sylee0506** [comment]
Did you deployed again on our main version?.?

**Comment by tranHieuDev23** [comment]
No, I deploy it on the 2.0 version so that other people can test it without interfering with the main one. 
Once this is merged to master then I can deploy it to the main version

**Comment by sylee0506** [comment]
Ok, I will test Korean characters seperately and if the issue still comes out, I will enroll it on Issue tab.

**Pull request merged**
